# Generated by Django 5.1.3 on 2024-12-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bids_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Magical', 'Magical')], max_length=50),
        ),
    ]
