# Generated by Django 5.1.3 on 2024-12-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'verbose_name': 'bid'},
        ),
    ]
