# Generated by Django 5.1.3 on 2024-12-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_bidder_bids_minimmum_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='minimmum_bid',
        ),
    ]
