# Generated by Django 5.1.3 on 2025-01-24 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="comments",
            name="commenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_on_listing",
                to="auctions.listing",
            ),
        ),
    ]
