# Generated by Django 5.1.3 on 2025-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_comments_comment_comments_commenter_comments_listing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name": "comment"},
        ),
        migrations.AddField(
            model_name="comments",
            name="posted",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
