# Generated by Django 5.1.3 on 2025-01-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_comments_options_comments_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="Active",
            field=models.BooleanField(default=True),
        ),
    ]
