# Generated by Django 5.1.3 on 2025-01-27 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_listing_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watch_lister",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
